# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# This file is always loaded, so it is encouraged to keep it light-weight.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # Include text for helper methods defined using `chain` in custom matchers
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # Prevents from mocking or stubbing a method that does not exist on a real object
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # This causes shared context metadata to be inherited by the metadata hash of host groups and examples
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Run specs in random order to surface order dependencies.
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  Kernel.srand config.seed
end
